// website/islands-preact/counter.jsx
import { useState } from "preact/hooks";
import "./counter.css";

export default function Counter({ initial = 0 }) {
	const [count, setCount] = useState(initial);

	return (
		<div class="counter-preact">
			<h3>Preact Counter Island</h3>
			<p>Count: {count}</p>
			<div class="buttons">
				<button onClick={() => setCount(count - 1)}>−</button>
				<button onClick={() => setCount(count + 1)}>+</button>
				<button onClick={() => setCount(initial)}>Reset</button>
			</div>
		</div>
	);
}

// website/islands-solid/counter.jsx
import { createSignal } from "solid-js";
import "./counter.css";

export default function Counter() {
	const [count, setCount] = createSignal(0);

	return (
		<div class="counter-solid">
			<h3>Solid Counter Island</h3>
			<p>Count: {count()}</p>
			<div class="buttons">
				<button onClick={() => setCount(count() - 1)}>−</button>
				<button onClick={() => setCount(count() + 1)}>+</button>
				<button onClick={() => setCount(0)}>Reset</button>
			</div>
		</div>
	);
}
