// website/islands/solid/counter.tsx
import { createSignal } from "solid-js";
import "./counter.css";

const Counter = ({ initial }: { initial?: number }) => {
	const [count, setCount] = createSignal<number>(initial ?? 0);

	return (
		<div class="solid-counter">
			<h3>Solid Counter Island</h3>
			<p>Count: {count()}</p>
			<div class="buttons">
				<button onClick={() => setCount(count() - 1)}>−</button>
				<button onClick={() => setCount(count() + 1)}>+</button>
				<button onClick={() => setCount(0)}>Reset</button>
			</div>
		</div>
	);
};

export default Counter;

// website/islands-preact/counter.tsx
import { useState } from "preact/hooks";
import type { FunctionComponent } from "preact";
import "./counter.css";

interface CounterProps {
	initial?: number;
}

const Counter: FunctionComponent<CounterProps> = ({ initial = 0 }) => {
	const [count, setCount] = useState<number>(initial);

	return (
		<div class="counter-preact">
			<h3>Preact Counter Island</h3>
			<p>Count: {count}</p>
			<div class="buttons">
				<button onClick={() => setCount(count - 1)}>−</button>
				<button onClick={() => setCount(count + 1)}>+</button>
				<button onClick={() => setCount(initial)}>Reset</button>
			</div>
		</div>
	);
};

export default Counter;
